"""reliability controls

Revision ID: 2fe944769727
Revises: e646a51c241b
Create Date: 2026-08-20 11:42:56.248084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fe944769727'
down_revision: Union[str, Sequence[str], None] = 'e646a51c241b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_reports', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_unique_constraint('uq_org_user_idempotency', 'organization_reports', ['organization_id', 'created_by', 'idempotency_key'])
    op.add_column('tasks', sa.Column('version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'version')
    op.drop_constraint('uq_org_user_idempotency', 'organization_reports', type_='unique')
    op.drop_column('organization_reports', 'idempotency_key')
    # ### end Alembic commands ###
