"""add organization reports

Revision ID: 36e2eab0972d
Revises: f73c9ebf27b2
Create Date: 2026-08-20 11:25:28.976563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e2eab0972d'
down_revision: Union[str, Sequence[str], None] = 'f73c9ebf27b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='reportstatus'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('summary_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_reports_organization_id'), 'organization_reports', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_reports_organization_id'), table_name='organization_reports')
    op.drop_table('organization_reports')
    # ### end Alembic commands ###
