"""add role to membership

Revision ID: e42ff95ae55d
Revises: d904efb2bb8d
Create Date: 2026-08-19 23:22:18.819795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e42ff95ae55d'
down_revision: Union[str, Sequence[str], None] = 'd904efb2bb8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_memberships', sa.Column('role', sa.String(length=50), server_default='MEMBER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_memberships', 'role')
    # ### end Alembic commands ###
