"""add timestamps to report

Revision ID: e646a51c241b
Revises: 36e2eab0972d
Create Date: 2026-08-20 11:28:51.292205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e646a51c241b'
down_revision: Union[str, Sequence[str], None] = '36e2eab0972d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_reports', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('organization_reports', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_reports', 'updated_at')
    op.drop_column('organization_reports', 'created_at')
    # ### end Alembic commands ###
